"""Tool: search_olive_documentation.

Semantic search over the local Olive knowledge base (and optional live docs),
with keyword fallback when nothing scores above the embedding threshold.
"""

from __future__ import annotations

import json
import logging
import re
import threading
import time
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import numpy as np

from . import KB_DIR
from .embeddings import (
    DEFAULT_THRESHOLD,
    EMBEDDING_DIM,
    build_kb_index,
    semantic_search,
)
from .retrieval import (
    budget_degraded_reason,
    get_retrieval_mode,
    get_semantic_budget_ms,
    merge_retrieval_meta,
    retrieval_meta,
    run_with_budget,
)

logger = logging.getLogger(__name__)

# Files that are generated by update_kb.py / expand_kb.py and must not be
# searched as KB. Including them would drift the content hash from the shipped
# index on every refresh run (refresh_metadata.json carries run timestamps).
_EXCLUDED_KB_FILES = {
    "update_report.json",
    "candidate_quirks.json",
    "refresh_metadata.json",
}

# Cache live docs for one hour so repeated searches do not hammer the network.
_LIVE_CACHE: dict[str, str] = {}
_LIVE_CACHE_TTL_SECONDS = 3600
_LAST_FETCH_TIME = 0.0
_LIVE_FETCH_LOCK = threading.Lock()
# Monotonic generation so out-of-order HTTP completions cannot overwrite a
# fresher cache entry started later.
_LIVE_FETCH_GENERATION = 0
# Generation number of the fetch that last actually published to _LIVE_CACHE.
# Tracking this (rather than comparing against _LIVE_FETCH_GENERATION, the
# highest *started* generation) means an older fetch that succeeds is not
# discarded just because a newer generation started and then failed.
_LIVE_FETCH_PUBLISHED_GENERATION = 0

# Live snippet embedding cache (tied to _LAST_FETCH_TIME).
_LIVE_SNIPPETS: list[tuple[str, str]] = []
_LIVE_EMBEDDINGS: np.ndarray | None = None
_LIVE_EMBED_CACHE_TIME = -1.0
_LIVE_INDEX_LOCK = threading.Lock()

# Local KB embedding index (invalidated when any KB JSON mtime or file count changes).
_KB_TEXTS: list[tuple[str, str]] = []
_KB_EMBEDDINGS: np.ndarray | None = None
_KB_INDEX_MTIME: tuple[float, int] = (-1.0, -1)
_KB_INDEX_LOCK = threading.Lock()


def _flatten(obj: Any, prefix: str = "") -> list[tuple[str, str]]:
    """Flatten a JSON object into (key-path, text) pairs for search."""
    results: list[tuple[str, str]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            results.extend(_flatten(v, f"{prefix}.{k}"))
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            results.extend(_flatten(item, f"{prefix}[{i}]"))
    elif isinstance(obj, str):
        results.append((prefix, obj))
    return results


def _iter_kb_json_files() -> Iterator[Path]:
    """Yield searchable KB JSON paths in a stable, sorted order.

    ``Path.glob`` order is OS-dependent; indexing and content hashing must
    iterate in a deterministic order so shipped indexes match across platforms.

    Security: resolved paths are validated to stay within KB_DIR, preventing
    symlink-based path traversal.
    """
    kb_dir_resolved = KB_DIR.resolve()
    for file in sorted(KB_DIR.glob("*.json"), key=lambda p: p.name):
        if file.name in _EXCLUDED_KB_FILES:
            continue
        # Path traversal protection: reject symlinks or paths resolving outside KB_DIR.
        resolved = file.resolve()
        if not resolved.is_relative_to(kb_dir_resolved):
            logger.warning("KB file %s resolves outside KB_DIR — skipping (path traversal guard)", file.name)
            continue
        yield file


def _load_kb_text() -> list[tuple[str, str]]:
    """
    Load and flatten searchable JSON knowledge-base files.

    Returns:
        list[tuple[str, str]]: Key-path and text pairs extracted from successfully loaded files.
    """
    all_text: list[tuple[str, str]] = []
    for file in _iter_kb_json_files():
        try:
            with open(file, encoding="utf-8") as f:
                data = json.load(f)
            for path, text in _flatten(data, prefix=file.stem):
                all_text.append((path, text))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            logger.warning("Skipping KB file %s: %s", file.name, exc)
            continue
    return all_text


def _kb_max_mtime() -> tuple[float, int]:
    """Return (max mtime, file count) for searchable KB JSON files.

    The count makes deletions and back-dated additions visible, since a
    deletion alone would otherwise leave the max mtime unchanged.
    """
    mtimes: list[float] = []
    for file in _iter_kb_json_files():
        try:
            mtimes.append(file.stat().st_mtime)
        except OSError as exc:
            logger.warning("Cannot stat KB file %s: %s", file.name, exc)
            continue
    return (max(mtimes) if mtimes else 0.0, len(mtimes))


def get_or_build_kb_index() -> tuple[list[tuple[str, str]], np.ndarray]:
    """Loads or builds the local knowledge-base text and embedding index, using a matching shipped index when available.

    Returns:
        tuple[list[tuple[str, str]], np.ndarray]: The knowledge-base text entries and their embedding matrix.
    """
    global _KB_TEXTS, _KB_EMBEDDINGS, _KB_INDEX_MTIME

    with _KB_INDEX_LOCK:
        current_mtime = _kb_max_mtime()
        if _KB_EMBEDDINGS is not None and _KB_TEXTS is not None and current_mtime == _KB_INDEX_MTIME:
            return _KB_TEXTS, _KB_EMBEDDINGS

    # Capture mtime at load time; only publish if it is still current later.
    build_mtime = _kb_max_mtime()
    texts = _load_kb_text()

    from .index_store import content_hash_pairs, load_pair_index

    expected = content_hash_pairs(texts)
    shipped = load_pair_index("docs_kb", expected)
    if shipped is not None:
        texts, embeddings = shipped
    elif not texts:
        embeddings = np.zeros((0, EMBEDDING_DIM), dtype=np.float32)
    else:
        embeddings = build_kb_index([t for _, t in texts])

    with _KB_INDEX_LOCK:
        current_mtime = _kb_max_mtime()
        # Another thread may have already published a valid index for the current mtime.
        if _KB_EMBEDDINGS is not None and _KB_TEXTS is not None and current_mtime == _KB_INDEX_MTIME:
            return _KB_TEXTS, _KB_EMBEDDINGS

        if current_mtime != build_mtime:
            # KB changed mid-build: return this result without poisoning the cache
            # (stale content must not be stamped with the newer mtime).
            return texts, embeddings

        _KB_TEXTS = texts
        _KB_EMBEDDINGS = embeddings
        _KB_INDEX_MTIME = build_mtime
        return _KB_TEXTS, _KB_EMBEDDINGS


# Back-compat alias for internal callers / tests.
_get_kb_index = get_or_build_kb_index


def _score_terms(text: str, terms: list[str]) -> int:
    text_lower = text.lower()
    return sum(1 for term in terms if term in text_lower)


def _keyword_search(
    entries: list[tuple[str, str]],
    terms: list[str],
    top_k: int,
) -> list[dict[str, Any]]:
    """
    Find entries whose text contains one or more search terms.

    Parameters:
        entries (list[tuple[str, str]]): Source and text pairs to search.
        terms (list[str]): Terms to match as case-insensitive substrings.
        top_k (int): Maximum number of results to return.

    Returns:
        list[dict[str, Any]]: Matching results ranked by the proportion of terms
        found, each containing the source, a text snippet, and its relevance score.
    """
    if not terms or top_k <= 0:
        return []
    denom = max(1, len(terms))
    scored: list[dict[str, Any]] = []
    for path, text in entries:
        hits = _score_terms(text, terms)
        if hits == 0:
            continue
        scored.append(
            {
                "source": path,
                "snippet": text[:300],
                "relevance": hits / denom,
            }
        )
    scored.sort(key=lambda x: x["relevance"], reverse=True)
    return scored[:top_k]


def _search_local(
    query: str,
    top_k: int,
    *,
    mode: str | None = None,
    budget_ms: int | None = None,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Search the local knowledge base using the selected retrieval mode.

    Parameters:
        query (str): Search terms.
        top_k (int): Maximum number of results to return.
        mode (str | None): Retrieval mode override.
        budget_ms (int | None): Explicit auto-mode semantic budget in milliseconds.
                ``None`` derives from ``OLIVE_MCP_SEMANTIC_BUDGET_MS`` (``0`` there means
                unlimited). When the caller passes an explicit value, ``0`` means the
                shared per-request budget is exhausted and forces the keyword path
                (never treated as unlimited).

    Returns:
        tuple[list[dict[str, Any]], dict[str, Any]]: Search results and metadata
        describing the effective retrieval mode and any fallback.
    """
    terms = [t.lower() for t in query.split() if t]
    resolved = get_retrieval_mode(mode)

    if resolved == "keyword":
        return (
            _keyword_search(_load_kb_text(), terms, top_k),
            retrieval_meta(mode=resolved, effective="keyword"),
        )

    # Auto must budget even when the embedding model is already warm: a missing,
    # stale, or force-rebuilt local index can still encode the full KB.
    use_budget = resolved == "auto"
    if use_budget:
        if budget_ms is None:
            effective_budget_ms = get_semantic_budget_ms()
        elif budget_ms == 0:
            # Shared request budget exhausted — keyword only (not unlimited).
            return (
                _keyword_search(_load_kb_text(), terms, top_k),
                retrieval_meta(
                    mode=resolved,
                    effective="keyword",
                    degraded=True,
                    reason="semantic_budget_exceeded",
                ),
            )
        else:
            effective_budget_ms = budget_ms
    else:
        effective_budget_ms = 0  # semantic mode: unlimited via run_with_budget

    def _semantic() -> tuple[list[dict[str, Any]], str]:
        """Semantic local search; returns (hits, effective_mode)."""
        kb_texts, embeddings = get_or_build_kb_index()
        results = semantic_search(
            query,
            kb_texts,
            embeddings,
            top_k,
            threshold=DEFAULT_THRESHOLD,
        )
        if results:
            return results, "hybrid"
        return _keyword_search(kb_texts, terms, top_k), "keyword"

    try:
        result, outcome = run_with_budget(_semantic, effective_budget_ms)
        if outcome != "ok":
            reason = budget_degraded_reason(outcome)
            if outcome == "busy":
                logger.warning(
                    "Semantic local search busy (single-flight in progress); keyword fallback",
                )
            else:
                logger.warning(
                    "Semantic local search exceeded budget (%sms); keyword fallback",
                    effective_budget_ms,
                )
            return (
                _keyword_search(_load_kb_text(), terms, top_k),
                retrieval_meta(
                    mode=resolved,
                    effective="keyword",
                    degraded=True,
                    reason=reason,
                ),
            )
        hits, effective = result
        return hits, retrieval_meta(mode=resolved, effective=effective)
    except Exception:
        logger.debug("Semantic local KB search failed; falling back to keyword search", exc_info=True)
        return (
            _keyword_search(_load_kb_text(), terms, top_k),
            retrieval_meta(
                mode=resolved,
                effective="keyword",
                degraded=True,
                reason="semantic_error",
            ),
        )


def _fetch_live_docs() -> tuple[dict[str, str], float]:
    """
    Fetch and cache the live Olive documentation landing page.

    Concurrent fetches publish only results from the latest completed generation.

    Returns:
        tuple[dict[str, str], float]: The cached documentation pages and their
        cache timestamp. Stale cached pages are returned when fetching fails.
    """
    global _LIVE_CACHE, _LAST_FETCH_TIME, _LIVE_FETCH_GENERATION, _LIVE_FETCH_PUBLISHED_GENERATION

    with _LIVE_FETCH_LOCK:
        now = time.monotonic()
        if _LIVE_CACHE and (now - _LAST_FETCH_TIME) < _LIVE_CACHE_TTL_SECONDS:
            return dict(_LIVE_CACHE), _LAST_FETCH_TIME
        _LIVE_FETCH_GENERATION += 1
        my_generation = _LIVE_FETCH_GENERATION

    try:
        # Lazy import: BeautifulSoup/requests are optional for local-KB-only search.
        from ..fetchers.official_docs_fetcher import fetch_official_docs

        result = fetch_official_docs(pages=["index"])
        if result.get("status") in ("ok", "partial"):
            pages = result.get("pages", {})
            fetched = {k: v for k, v in pages.items() if isinstance(v, str)}
            if fetched:
                with _LIVE_FETCH_LOCK:
                    # Publish unless a generation newer than this one has
                    # already published. Comparing against the last
                    # *published* generation (not the highest *started* one)
                    # means an older fetch that succeeds still gets to
                    # publish when a newer sibling generation started but
                    # never actually completed successfully.
                    if my_generation >= _LIVE_FETCH_PUBLISHED_GENERATION:
                        _LIVE_CACHE = fetched
                        _LAST_FETCH_TIME = time.monotonic()
                        _LIVE_FETCH_PUBLISHED_GENERATION = my_generation
    except Exception:
        logger.debug("Live docs fetch failed; keeping stale cache", exc_info=True)

    with _LIVE_FETCH_LOCK:
        return dict(_LIVE_CACHE), _LAST_FETCH_TIME


def _split_live_snippets(pages: dict[str, str]) -> list[tuple[str, str]]:
    """Break live page text into searchable snippets."""
    snippets: list[tuple[str, str]] = []
    for page, text in pages.items():
        for paragraph in text.split("\n\n"):
            paragraph = " ".join(paragraph.split()).strip()
            if paragraph:
                snippets.append((f"live:{page}", paragraph))
    return snippets


def _get_live_index() -> tuple[list[tuple[str, str]], np.ndarray]:
    """Retrieve live documentation snippets and their embeddings, rebuilding the index when cached content changes.

    Returns:
        A tuple containing live documentation snippets and their embedding matrix.
    """
    global _LIVE_SNIPPETS, _LIVE_EMBEDDINGS, _LIVE_EMBED_CACHE_TIME

    pages, fetch_time = _fetch_live_docs()

    with _LIVE_INDEX_LOCK:
        if _LIVE_EMBEDDINGS is not None and fetch_time == _LIVE_EMBED_CACHE_TIME:
            return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS

    snippets = _split_live_snippets(pages) if pages else []
    if not snippets:
        embeddings: np.ndarray = np.zeros((0, EMBEDDING_DIM), dtype=np.float32)
    else:
        embeddings = build_kb_index([t for _, t in snippets])

    with _LIVE_INDEX_LOCK:
        if _LIVE_EMBEDDINGS is not None and fetch_time == _LIVE_EMBED_CACHE_TIME:
            return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS
        if _LIVE_EMBEDDINGS is not None and fetch_time < _LIVE_EMBED_CACHE_TIME:
            # A newer generation already published while this one was
            # encoding; discard this stale build rather than clobber it.
            return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS

        _LIVE_SNIPPETS = snippets
        _LIVE_EMBEDDINGS = embeddings
        _LIVE_EMBED_CACHE_TIME = fetch_time
        return _LIVE_SNIPPETS, _LIVE_EMBEDDINGS


def _search_live(
    query: str,
    top_k: int,
    *,
    mode: str | None = None,
    budget_ms: int | None = None,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Search live Olive documentation using the resolved retrieval mode.

    ``mode="keyword"`` fetches and splits live pages, then runs
    :func:`_keyword_search` only — it must not build the live embedding index
    or call :func:`semantic_search`.

    ``budget_ms`` is the remaining auto-mode semantic budget for this request.
    An explicit ``0`` forces the keyword path (shared budget exhausted). ``None``
    derives from ``OLIVE_MCP_SEMANTIC_BUDGET_MS`` (where ``0`` means unlimited).

    Returns results plus retrieval metadata so callers can surface live
    degradation (budget/timeout) in the merged response.
    """
    terms = [t.lower() for t in query.split() if t]
    resolved = get_retrieval_mode(mode)

    def _keyword_live() -> list[dict[str, Any]]:
        """Fetch live pages and rank snippets by keyword overlap (no embeddings)."""
        try:
            pages, _ = _fetch_live_docs()
            if not pages:
                return []
            return _keyword_search(_split_live_snippets(pages), terms, top_k)
        except Exception:
            logger.debug("Live-doc keyword search failed", exc_info=True)
            return []

    # Keyword mode: never touch the embedding model / live embedding index.
    if resolved == "keyword":
        return _keyword_live(), retrieval_meta(mode=resolved, effective="keyword")

    # Auto budgets even when the model is warm: live fetch/index build can still
    # be cold after local search already loaded the embedding model.
    use_budget = resolved == "auto"
    if use_budget:
        if budget_ms is None:
            effective_budget_ms = get_semantic_budget_ms()
        elif budget_ms == 0:
            # Shared request budget exhausted — keyword only (not unlimited).
            return (
                _keyword_live(),
                retrieval_meta(
                    mode=resolved,
                    effective="keyword",
                    degraded=True,
                    reason="semantic_budget_exceeded",
                ),
            )
        else:
            effective_budget_ms = budget_ms
    else:
        effective_budget_ms = 0  # semantic mode: unlimited via run_with_budget

    def _semantic_live() -> tuple[list[dict[str, Any]], str]:
        snippets, embeddings = _get_live_index()
        if not snippets:
            return [], "keyword"
        results = semantic_search(
            query,
            snippets,
            embeddings,
            top_k,
            threshold=DEFAULT_THRESHOLD,
        )
        if results:
            return results, "hybrid"
        return _keyword_search(snippets, terms, top_k), "keyword"

    try:
        result, outcome = run_with_budget(_semantic_live, effective_budget_ms)
        if outcome != "ok":
            reason = budget_degraded_reason(outcome)
            if outcome == "busy":
                logger.warning(
                    "Semantic live search busy (single-flight in progress); keyword fallback",
                )
            else:
                logger.warning(
                    "Semantic live search exceeded budget (%sms); keyword fallback",
                    effective_budget_ms,
                )
            return (
                _keyword_live(),
                retrieval_meta(
                    mode=resolved,
                    effective="keyword",
                    degraded=True,
                    reason=reason,
                ),
            )
        hits, effective = result
        return hits, retrieval_meta(mode=resolved, effective=effective)
    except Exception:
        logger.debug("Semantic live-doc search failed; falling back to keyword search", exc_info=True)
        return (
            _keyword_live(),
            retrieval_meta(
                mode=resolved,
                effective="keyword",
                degraded=True,
                reason="semantic_error",
            ),
        )


def search_olive_documentation(
    query: str,
    top_k: int = 5,
    live: bool = True,
    mode: str = "",
) -> dict[str, Any]:
    """Search the local Olive knowledge base and optionally the live Olive documentation.

    Args:
        query: Search terms, such as ``"calibrate static quantization"``.
        top_k: Maximum number of results to return; must be greater than or equal to zero.
        live: Whether to include results from the live Olive documentation.
        mode: Retrieval mode: ``"auto"``, ``"keyword"``, or ``"semantic"``. An empty
            value uses the default mode. The resolved mode is passed to both the
            local and live search paths so ``keyword`` never starts embedding work
            on either side.

    Returns:
        A dictionary containing the query, ranked results, result count, explanatory
        note, and retrieval metadata.

    Raises:
        ValueError: If ``top_k`` is negative.
    """
    if top_k < 0:
        raise ValueError(f"top_k must be >= 0, got {top_k}")

    # Input sanitization: limit length, normalize whitespace controls to spaces
    # (preserving token boundaries), then strip non-whitespace control chars.
    raw = query[:2000]
    raw = re.sub(r"[\t\n\r\x0b\x0c]", " ", raw)
    query = re.sub(r"[\x00-\x08\x0e-\x1f\x7f]", "", raw).strip()

    mode_arg = mode if (mode or "").strip() else None
    resolved_mode = get_retrieval_mode(mode_arg)
    terms = [t.lower() for t in query.split() if t]
    if not terms:
        return {
            "query": query,
            "count": 0,
            "results": [],
            "note": "Empty query.",
            "retrieval": retrieval_meta(
                mode=resolved_mode,
                effective="none",
            ),
        }
    if top_k == 0:
        return {
            "query": query,
            "count": 0,
            "results": [],
            "note": "No results requested.",
            "retrieval": retrieval_meta(
                mode=resolved_mode,
                effective="none",
            ),
        }

    per_source = max(top_k * 2, 10)

    # One per-request semantic deadline for auto mode (local + live share it).
    # Env budget 0 stays unlimited (shared_deadline=None → budget_ms=None).
    shared_deadline: float | None = None
    if resolved_mode == "auto":
        total_budget_ms = get_semantic_budget_ms()
        if total_budget_ms > 0:
            shared_deadline = time.monotonic() + (total_budget_ms / 1000.0)

    def _remaining_budget_ms() -> int | None:
        if shared_deadline is None:
            return None
        return max(0, int((shared_deadline - time.monotonic()) * 1000))

    # Pass the already-resolved mode so local + live stay in lockstep (e.g. keyword
    # never loads embeddings even when OLIVE_MCP_RETRIEVAL_MODE would differ).
    local_results, retrieval = _search_local(
        query,
        per_source,
        mode=resolved_mode,
        budget_ms=_remaining_budget_ms(),
    )
    if live:
        live_results, live_retrieval = _search_live(
            query,
            per_source,
            mode=resolved_mode,
            budget_ms=_remaining_budget_ms(),
        )
        retrieval = merge_retrieval_meta(retrieval, live_retrieval)
    else:
        live_results = []

    combined = local_results + live_results
    combined.sort(key=lambda x: (-x["relevance"], 0 if x["source"].startswith("live:") else 1))

    # `combined` is already sorted with live sources preferred on relevance
    # ties, so the top-k slice already surfaces a live result whenever one is
    # genuinely competitive with the kept local results — no separate
    # "reserve a freshness slot" step is needed (an earlier version of that
    # step was unreachable dead code given this tie-break).
    results = combined[:top_k]

    return {
        "query": query,
        "count": len(combined),
        "results": results,
        "note": ("Merged local knowledge base and live Olive docs results. Live docs are cached for one hour."),
        "retrieval": retrieval,
    }
